import { enrichedExercises, type EnrichedExercise } from "@/lib/data/enriched-content"

// Données statiques pour les 21 exercices de la plateforme
export interface StaticExercise {
  id: number
  title: string
  description: string
  image: string
  difficulty: "Facile" | "Moyen" | "Difficile"
  time: string
  exercises: number
  hasCorrection: boolean
  level: "Collège" | "Lycée"
  classe: string
}

export const staticExercisesData: { [key: number]: StaticExercise } = {
  1: {
    id: 1,
    title: "Opérations sur les décimaux",
    description: "Exercices d'addition, soustraction, multiplication et division",
    image: "/placeholder.svg?height=200&width=400",
    difficulty: "Facile",
    time: "30 min",
    exercises: 15,
    hasCorrection: true,
    level: "Collège",
    classe: "6ème",
  },
  2: {
    id: 2,
    title: "Fractions simples",
    description: "Comparaison et opérations sur les fractions",
    image: "/placeholder.svg?height=200&width=400",
    difficulty: "Moyen",
    time: "45 min",
    exercises: 12,
    hasCorrection: true,
    level: "Collège",
    classe: "6ème",
  },
  3: {
    id: 3,
    title: "Périmètres et aires",
    description: "Calcul de périmètres et d'aires de figures simples",
    image: "/placeholder.svg?height=200&width=400",
    difficulty: "Moyen",
    time: "40 min",
    exercises: 10,
    hasCorrection: true,
    level: "Collège",
    classe: "6ème",
  },
  4: {
    id: 4,
    title: "Nombres relatifs",
    description: "Addition et soustraction de nombres relatifs",
    image: "/placeholder.svg?height=200&width=400",
    difficulty: "Facile",
    time: "35 min",
    exercises: 14,
    hasCorrection: true,
    level: "Collège",
    classe: "5ème",
  },
  5: {
    id: 5,
    title: "Expressions littérales",
    description: "Calcul et simplification d'expressions",
    image: "/placeholder.svg?height=200&width=400",
    difficulty: "Difficile",
    time: "50 min",
    exercises: 8,
    hasCorrection: true,
    level: "Collège",
    classe: "5ème",
  },
  6: {
    id: 6,
    title: "Symétries",
    description: "Constructions de figures symétriques",
    image: "/placeholder.svg?height=200&width=400",
    difficulty: "Moyen",
    time: "40 min",
    exercises: 12,
    hasCorrection: false,
    level: "Collège",
    classe: "5ème",
  },
  7: {
    id: 7,
    title: "Calcul littéral",
    description: "Développement et factorisation d'expressions",
    image: "/placeholder.svg?height=200&width=400",
    difficulty: "Moyen",
    time: "45 min",
    exercises: 10,
    hasCorrection: true,
    level: "Collège",
    classe: "4ème",
  },
  8: {
    id: 8,
    title: "Théorème de Pythagore",
    description: "Applications du théorème de Pythagore",
    image: "/placeholder.svg?height=200&width=400",
    difficulty: "Difficile",
    time: "55 min",
    exercises: 8,
    hasCorrection: true,
    level: "Collège",
    classe: "4ème",
  },
  9: {
    id: 9,
    title: "Proportionnalité",
    description: "Problèmes de proportionnalité et pourcentages",
    image: "/placeholder.svg?height=200&width=400",
    difficulty: "Moyen",
    time: "40 min",
    exercises: 12,
    hasCorrection: true,
    level: "Collège",
    classe: "4ème",
  },
  10: {
    id: 10,
    title: "Équations",
    description: "Résolution d'équations du premier degré",
    image: "/placeholder.svg?height=200&width=400",
    difficulty: "Moyen",
    time: "50 min",
    exercises: 15,
    hasCorrection: true,
    level: "Collège",
    classe: "3ème",
  },
  11: {
    id: 11,
    title: "Fonctions linéaires",
    description: "Représentation graphique et calculs",
    image: "/placeholder.svg?height=200&width=400",
    difficulty: "Difficile",
    time: "60 min",
    exercises: 10,
    hasCorrection: true,
    level: "Collège",
    classe: "3ème",
  },
  12: {
    id: 12,
    title: "Trigonométrie",
    description: "Calculs trigonométriques dans le triangle rectangle",
    image: "/placeholder.svg?height=200&width=400",
    difficulty: "Difficile",
    time: "55 min",
    exercises: 12,
    hasCorrection: true,
    level: "Collège",
    classe: "3ème",
  },
  13: {
    id: 13,
    title: "Calcul dans R",
    description: "Exercices sur les calculs dans l'ensemble des réels",
    image: "/placeholder.svg?height=200&width=400",
    difficulty: "Moyen",
    time: "45 min",
    exercises: 10,
    hasCorrection: true,
    level: "Lycée",
    classe: "2nde",
  },
  14: {
    id: 14,
    title: "Vecteurs",
    description: "Opérations vectorielles dans le plan",
    image: "/placeholder.svg?height=200&width=400",
    difficulty: "Difficile",
    time: "60 min",
    exercises: 8,
    hasCorrection: true,
    level: "Lycée",
    classe: "2nde",
  },
  15: {
    id: 15,
    title: "Statistiques",
    description: "Indicateurs de position et de dispersion",
    image: "/placeholder.svg?height=200&width=400",
    difficulty: "Moyen",
    time: "50 min",
    exercises: 12,
    hasCorrection: false,
    level: "Lycée",
    classe: "2nde",
  },
  22: {
    id: 22,
    title: "Calcul vectoriel",
    description: "Opérations vectorielles dans le plan",
    image: "/placeholder.svg?height=200&width=400",
    difficulty: "Difficile",
    time: "60 min",
    exercises: 8,
    hasCorrection: true,
    level: "Lycée",
    classe: "2nde",
  },
  23: {
    id: 23,
    title: "Second degrés",
    description: "Équations et fonctions du second degré",
    image: "/placeholder.svg?height=200&width=400",
    difficulty: "Moyen",
    time: "50 min",
    exercises: 12,
    hasCorrection: true,
    level: "Lycée",
    classe: "2nde",
  },
  24: {
    id: 24,
    title: "Barycentre",
    description: "Exercices sur le barycentre",
    image: "/placeholder.svg?height=200&width=400",
    difficulty: "Moyen",
    time: "45 min",
    exercises: 10,
    hasCorrection: true,
    level: "Lycée",
    classe: "2nde",
  },
  25: {
    id: 25,
    title: "Systemes",
    description: "Résolution de systèmes d'équations",
    image: "/placeholder.svg?height=200&width=400",
    difficulty: "Moyen",
    time: "50 min",
    exercises: 12,
    hasCorrection: true,
    level: "Lycée",
    classe: "2nde",
  },
  26: {
    id: 26,
    title: "Angles",
    description: "Exercices sur les angles",
    image: "/placeholder.svg?height=200&width=400",
    difficulty: "Moyen",
    time: "45 min",
    exercises: 10,
    hasCorrection: true,
    level: "Lycée",
    classe: "2nde",
  },
  27: {
    id: 27,
    title: "Fonctions",
    description: "Étude des fonctions",
    image: "/placeholder.svg?height=200&width=400",
    difficulty: "Moyen",
    time: "50 min",
    exercises: 12,
    hasCorrection: true,
    level: "Lycée",
    classe: "2nde",
  },
  28: {
    id: 28,
    title: "Polynomes",
    description: "Exercices sur les polynômes",
    image: "/placeholder.svg?height=200&width=400",
    difficulty: "Moyen",
    time: "45 min",
    exercises: 10,
    hasCorrection: true,
    level: "Lycée",
    classe: "2nde",
  },
  16: {
    id: 16,
    title: "Dérivées",
    description: "Calcul de dérivées et applications",
    image: "/placeholder.svg?height=200&width=400",
    difficulty: "Difficile",
    time: "65 min",
    exercises: 15,
    hasCorrection: true,
    level: "Lycée",
    classe: "1ère",
  },
  17: {
    id: 17,
    title: "Suites numériques",
    description: "Suites arithmétiques et géométriques",
    image: "/placeholder.svg?height=200&width=400",
    difficulty: "Moyen",
    time: "55 min",
    exercises: 12,
    hasCorrection: true,
    level: "Lycée",
    classe: "1ère",
  },
  18: {
    id: 18,
    title: "Probabilités",
    description: "Variables aléatoires et lois de probabilité",
    image: "/placeholder.svg?height=200&width=400",
    difficulty: "Difficile",
    time: "70 min",
    exercises: 10,
    hasCorrection: true,
    level: "Lycée",
    classe: "Terminale",
  },
  19: {
    id: 19,
    title: "Calcul intégral",
    description: "Calcul d'intégrales et applications",
    image: "/placeholder.svg?height=200&width=400",
    difficulty: "Difficile",
    time: "75 min",
    exercises: 12,
    hasCorrection: true,
    level: "Lycée",
    classe: "Terminale",
  },
  20: {
    id: 20,
    title: "Nombres complexes",
    description: "Opérations et applications géométriques",
    image: "/placeholder.svg?height=200&width=400",
    difficulty: "Difficile",
    time: "65 min",
    exercises: 10,
    hasCorrection: true,
    level: "Lycée",
    classe: "Terminale",
  },
  21: {
    id: 21,
    title: "Logarithmes",
    description: "Fonctions logarithmiques et exponentielles",
    image: "/placeholder.svg?height=200&width=400",
    difficulty: "Moyen",
    time: "60 min",
    exercises: 15,
    hasCorrection: true,
    level: "Lycée",
    classe: "Terminale",
  },
  29: {
    id: 29,
    title: "Angles orienté",
    description: "Exercices sur les angles orientés",
    image: "/placeholder.svg?height=200&width=400",
    difficulty: "Moyen",
    time: "50 min",
    exercises: 12,
    hasCorrection: true,
    level: "Lycée",
    classe: "1ère",
  },
  30: {
    id: 30,
    title: "Dénombrement",
    description: "Exercices de dénombrement",
    image: "/placeholder.svg?height=200&width=400",
    difficulty: "Moyen",
    time: "45 min",
    exercises: 10,
    hasCorrection: true,
    level: "Lycée",
    classe: "1ère",
  },
  32: {
    id: 32,
    title: "Équations, inéquations et systèmes",
    description: "Résolution d'équations, inéquations et systèmes",
    image: "/placeholder.svg?height=200&width=400",
    difficulty: "Moyen",
    time: "50 min",
    exercises: 12,
    hasCorrection: true,
    level: "Lycée",
    classe: "1ère",
  },
  33: {
    id: 33,
    title: "Fonctions",
    description: "Étude des fonctions",
    image: "/placeholder.svg?height=200&width=400",
    difficulty: "Moyen",
    time: "50 min",
    exercises: 12,
    hasCorrection: true,
    level: "Lycée",
    classe: "1ère",
  },
  34: {
    id: 34,
    title: "Identités et relations trigonométriques",
    description: "Exercices sur les identités trigonométriques",
    image: "/placeholder.svg?height=200&width=400",
    difficulty: "Moyen",
    time: "50 min",
    exercises: 12,
    hasCorrection: true,
    level: "Lycée",
    classe: "1ère",
  },
  35: {
    id: 35,
    title: "Limites et Continuité",
    description: "Exercices sur les limites et la continuité",
    image: "/placeholder.svg?height=200&width=400",
    difficulty: "Difficile",
    time: "60 min",
    exercises: 15,
    hasCorrection: true,
    level: "Lycée",
    classe: "1ère",
  },
  36: {
    id: 36,
    title: "Primitives",
    description: "Calcul de primitives",
    image: "/placeholder.svg?height=200&width=400",
    difficulty: "Moyen",
    time: "50 min",
    exercises: 12,
    hasCorrection: true,
    level: "Lycée",
    classe: "1ère",
  },
  38: {
    id: 38,
    title: "Transformations du plan",
    description: "Exercices sur les transformations du plan",
    image: "/placeholder.svg?height=200&width=400",
    difficulty: "Moyen",
    time: "50 min",
    exercises: 12,
    hasCorrection: true,
    level: "Lycée",
    classe: "1ère",
  },
  39: {
    id: 39,
    title: "Arithmétique",
    description: "Exercices d'arithmétique",
    image: "/placeholder.svg?height=200&width=400",
    difficulty: "Difficile",
    time: "60 min",
    exercises: 12,
    hasCorrection: true,
    level: "Lycée",
    classe: "Terminale",
  },
  41: {
    id: 41,
    title: "Dérivation TS1",
    description: "Dérivation pour Terminale S1",
    image: "/placeholder.svg?height=200&width=400",
    difficulty: "Difficile",
    time: "65 min",
    exercises: 15,
    hasCorrection: true,
    level: "Lycée",
    classe: "Terminale",
  },
  42: {
    id: 42,
    title: "Équations différentielles",
    description: "Résolution d'équations différentielles",
    image: "/placeholder.svg?height=200&width=400",
    difficulty: "Difficile",
    time: "70 min",
    exercises: 12,
    hasCorrection: true,
    level: "Lycée",
    classe: "Terminale",
  },
  43: {
    id: 43,
    title: "Fonctions exponentielles et logarithmes (TS1)",
    description: "Fonctions exponentielles et logarithmes",
    image: "/placeholder.svg?height=200&width=400",
    difficulty: "Difficile",
    time: "65 min",
    exercises: 12,
    hasCorrection: true,
    level: "Lycée",
    classe: "Terminale",
  },
  44: {
    id: 44,
    title: "Limites et continuité",
    description: "Limites et continuité",
    image: "/placeholder.svg?height=200&width=400",
    difficulty: "Difficile",
    time: "60 min",
    exercises: 12,
    hasCorrection: true,
    level: "Lycée",
    classe: "Terminale",
  },
  47: {
    id: 47,
    title: "Suites TS1",
    description: "Suites numériques pour Terminale S1",
    image: "/placeholder.svg?height=200&width=400",
    difficulty: "Moyen",
    time: "55 min",
    exercises: 12,
    hasCorrection: true,
    level: "Lycée",
    classe: "Terminale",
  },
  48: {
    id: 48,
    title: "Calcul intégral",
    description: "Calcul intégral pour Terminale S2",
    image: "/placeholder.svg?height=200&width=400",
    difficulty: "Difficile",
    time: "75 min",
    exercises: 12,
    hasCorrection: true,
    level: "Lycée",
    classe: "Terminale",
  },
  49: {
    id: 49,
    title: "Équations différentielles",
    description: "Équations différentielles pour Terminale S2",
    image: "/placeholder.svg?height=200&width=400",
    difficulty: "Difficile",
    time: "70 min",
    exercises: 12,
    hasCorrection: true,
    level: "Lycée",
    classe: "Terminale",
  },
  50: {
    id: 50,
    title: "Fonctions numériques",
    description: "Fonctions numériques",
    image: "/placeholder.svg?height=200&width=400",
    difficulty: "Moyen",
    time: "60 min",
    exercises: 12,
    hasCorrection: true,
    level: "Lycée",
    classe: "Terminale",
  },
  51: {
    id: 51,
    title: "Nombres complexes et similitudes",
    description: "Nombres complexes et similitudes",
    image: "/placeholder.svg?height=200&width=400",
    difficulty: "Difficile",
    time: "65 min",
    exercises: 12,
    hasCorrection: true,
    level: "Lycée",
    classe: "Terminale",
  },
  52: {
    id: 52,
    title: "Probabilités",
    description: "Probabilités pour Terminale S2",
    image: "/placeholder.svg?height=200&width=400",
    difficulty: "Difficile",
    time: "70 min",
    exercises: 10,
    hasCorrection: true,
    level: "Lycée",
    classe: "Terminale",
  },
  53: {
    id: 53,
    title: "Statistiques",
    description: "Statistiques",
    image: "/placeholder.svg?height=200&width=400",
    difficulty: "Moyen",
    time: "50 min",
    exercises: 12,
    hasCorrection: true,
    level: "Lycée",
    classe: "Terminale",
  },
  54: {
    id: 54,
    title: "Suites numériques",
    description: "Suites numériques pour Terminale S2",
    image: "/placeholder.svg?height=200&width=400",
    difficulty: "Moyen",
    time: "55 min",
    exercises: 12,
    hasCorrection: true,
    level: "Lycée",
    classe: "Terminale",
  },
}

const determineExerciseLevel = (classe: string): "Collège" | "Lycée" => {
  if (["6ème", "5ème", "4ème", "3ème"].includes(classe)) {
    return "Collège"
  }
  return "Lycée"
}

const normalizeDifficulty = (difficulty: EnrichedExercise["difficulty"]): "Facile" | "Moyen" | "Difficile" => {
  if (difficulty === "Facile" || difficulty === "Moyen" || difficulty === "Difficile") {
    return difficulty
  }
  return "Moyen"
}

for (const [classe, exercises] of Object.entries(enrichedExercises)) {
  exercises.forEach((exercise) => {
    if (staticExercisesData[exercise.id]) {
      return
    }

    staticExercisesData[exercise.id] = {
      id: exercise.id,
      title: exercise.title,
      description: exercise.description,
      image: "/images/exercice.jpg",
      difficulty: normalizeDifficulty(exercise.difficulty),
      time: exercise.time || "45 min",
      exercises: exercise.exercises || 10,
      hasCorrection: exercise.hasCorrection,
      level: determineExerciseLevel(classe),
      classe,
    }
  })
}

/**
 * Récupère un exercice statique par son ID
 */
export function getStaticExerciseById(exerciseId: number): StaticExercise | null {
  return staticExercisesData[exerciseId] || null
}

/**
 * Récupère tous les exercices statiques
 */
export function getAllStaticExercises(): StaticExercise[] {
  return Object.values(staticExercisesData)
}

/**
 * Récupère les exercices statiques par classe
 */
export function getStaticExercisesByClasse(classe: string): StaticExercise[] {
  return Object.values(staticExercisesData).filter(
    (exercise) => exercise.classe === classe
  )
}
